// Auto-generated by scripts/generate-supabase-env.js on 2025-12-02T00:44:07.069Z
// Source env file: .env

window.__NAEI_SUPABASE_CONFIG = Object.freeze({
  url: "https://vhplzwzzkeueyelaqftl.supabase.co",
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocGx6d3p6a2V1ZXllbGFxZnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjQwODUsImV4cCI6MjA3NjA0MDA4NX0.mBAwFmfSpqffvp1GGDHKvp-y_hukSZmF4GN-Ghnf--o",
  storageKeyBase: "sb-vhplzwzzkeueyelaqftl-auth-token"
});
